apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-engagement-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-engagement
  template:
    metadata:
      labels:
        app: student-engagement
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/vcc-assignment-452510/student-engagement-app/backend:latest
          env:
          - name: HF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: HF_API_TOKEN
                key: HF_API_TOKEN
          ports:
            - containerPort: 5000
