apiVersion: v1
kind: Service
metadata:
  name: student-engagement-service
spec:
  type: LoadBalancer
  selector:
    app: student-engagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
