apiVersion: v1
kind: Service
metadata:
  name: student-engagement-api-service
spec:
  selector:
    app: student-engagement-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
