version: '3.8'
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      HF_API_TOKEN: ${HF_API_TOKEN}
    volumes:
      - ./src:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"