name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build --build-arg HF_API_TOKEN=${{ secrets.HF_API_TOKEN }} \
          -f src/Dockerfile -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/student-engagement-app/backend:latest .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/student-engagement-app/backend:latest

      - name: Retrieve cluster credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone us-central1-c

      - name: Deploy to Kubernetes
        env:
          HF_API_TOKEN : ${{ secrets.HF_API_TOKEN }}
        run: |
          gcloud components install gke-gcloud-auth-plugin
          echo "export HF_API_TOKEN=${HF_API_TOKEN}" >> $GITHUB_ENV
          kubectl apply -f src/configs/
          